### ISSUE TITLE
Translating text throwing a 500 error.

### ISSUE THREAD

**Issue by rachelnicole** [watson-developer-cloud/language-translator-nodejs#2]
I'm using the demo code from this repo combined with demo code from the speech to text on the same page, and no matter what I do, even passing in the parameters manually,  the server is giving me a 500 error on POST when it tries to hit the api/translate endpoint.

http://oddestthingintheuniverse.mybluemix.net/

My code setup in app.js is the following: 

If anyone could help point me in the right direction it'd be greatly appreciated. I can also link to a full source of the repo if needed.

``` javascript
// For local development, put username and password in config
// or store in your environment
var config = {
  version: 'v1',
  url: 'https://stream.watsonplatform.net/speech-to-text/api',
// removed username and password for code example
  username: username,
  password: password
};

// if bluemix credentials exists, then override local
var speechCredentials = extend(config, bluemix.getServiceCreds('speech_to_text'));
var authorization = watson.authorization(speechCredentials);

// if bluemix credentials exists, then override local
var languageCredentials =  extend({
// removed username and password for code example
  username: username,
  password: password,
  version: 'v2'
}, bluemix.getServiceCreds('language-translation')); // VCAP_SERVICES

var language_translation = watson.language_translation(languageCredentials);


// Setup static public directory
app.use(express.static(path.join(__dirname , './public')));
// render index page
app.get('/', function(req, res) {
  res.render('index');
});

// Get token from Watson for the speech recognition using your credentials
app.get('/token', function(req, res) {
  authorization.getToken({url: speechCredentials.url}, function(err, token) {
    if (err) {
      console.log('error:', err);
      res.status(err.code);
    }

    res.send(token);
  });
});


// Gets the model data for the language translation

app.get('/api/models', function(req, res, next) {
  console.log('/v2/models');
  language_translation.getModels({}, function(err, models) {
    if (err) {
      return next(err);
    }
    else {
      res.json(models);
    }
  });
});


// Post request for the input box to detect language you're typing in.

app.post('/api/identify', function(req, res, next) {
  console.log('/v2/identify');
  var params = {
    text: req.body.textData,
    'X-WDC-PL-OPT-OUT': req.header('X-WDC-PL-OPT-OUT')
  };
  language_translation.identify(params, function(err, models) {
      if (err) {
        return next(err);
      }
      else {
        res.json(models);
      }
  });
});

app.get('/api/identifiable_languages', function(req, res, next) {
  console.log('/v2/identifiable_languages');
  language_translation.getIdentifiableLanguages({}, function(err, models) {
    if (err) {
      return next(err);
    }
    else {
      res.json(models);
    }
  });
});

app.post('/api/translate', function(req, res, next) {
  console.log('/v2/translate');
  var params = extend({ 'X-WDC-PL-OPT-OUT': req.header('X-WDC-PL-OPT-OUT')}, req.body);
  language_translation.translate(params, function(err, models) {
    if (err) {
      return next(err);
    }
    else
      res.json(models);
  });
});
```

The error I'm getting keeps on being 

``` javascript
"Error: Missing required parameters: model_id or source and target<br> &nbsp; &nbsp;at LanguageTranslation.translate (/home/vcap/app/node_modules/watson-developer-cloud/services/language_translation/v2.js:65:14)<br> &nbsp; &nbsp;at port (/home/vcap/app/app.js:120:24)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:82:5)<br> &nbsp; &nbsp;at next (/home/vcap/app/node_modules/express/lib/router/route.js:100:13)<br> &nbsp; &nbsp;at Route.dispatch (/home/vcap/app/node_modules/express/lib/router/route.js:81:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:82:5)<br> &nbsp; &nbsp;at /home/vcap/app/node_modules/express/lib/router/index.js:233:24<br> &nbsp; &nbsp;at Function.proto.process_params (/home/vcap/app/node_modules/express/lib/router/index.js:311:12)<br> &nbsp; &nbsp;at /home/vcap/app/node_modules/express/lib/router/index.js:227:12<br> &nbsp; &nbsp;at Function.match_layer (/home/vcap/app/node_modules/express/lib/router/index.js:294:3)"
```

![screen shot 2015-07-31 at 3 42 35 pm](https://cloud.githubusercontent.com/assets/228230/9017525/1e0747ac-37a5-11e5-832a-3614e7fdc23e.png)

**Comment by germanattanasio** [comment]
The error you are getting seems to be a missing parameter. Check the call to `translate` you need to send `source`,`target` and `text` or `model_id` and `text`

**Comment by rachelnicole** [comment]
@germanattanasio Yes, that's what the error said. 

However, I tried passing in the parameters manually according to what it said it was missing, and I ended up getting a 502 Error.

**Comment by germanattanasio** [comment]
can you paste the parameters you are sending?

**Comment by rachelnicole** [comment]
@germanattanasio Sure I have to wait until I get back into the office tomorrow and I'm on my work machine but I'll get back to you then.

**Comment by rachelnicole** [comment]
@germanattanasio I actually figured out the issue!

I had forgotten to add in the `require('./config/express')(app);` in when I was merging the two services app.js files. 

Closing issue :)
