### ISSUE TITLE
deploy problems

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/language-translator-nodejs#35]
Hi bros

i do this:

```
  url: 'https://gateway.watsonplatform.net/language-translator/api',
  username: 'XXX',
  password: 'YYY'
```

and `nano .env`

```
# see http://www.ibm.com/watson/developercloud/doc/getting_started/gs-credentia$
LANGUAGE_TRANSLATOR_URL=https://gateway.watsonplatform.net/language-translator/api
LANGUAGE_TRANSLATOR_USERNAME=XXX
LANGUAGE_TRANSLATOR_PASSWORD=YYY
```

Its show me this error in console:

```
Error: listen EADDRINUSE :::3005
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventEmitter.listen (/home/felipe/language-translation-nodejs/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/felipe/language-translation-nodejs/app.js:93:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

How can i solve it

**Comment by germanattanasio** [comment]
just stop the other node instance you have running. The error is saying that `3005` is already in use.

**Comment by johnfelipe** [comment]
solved, tnks
